# Generated by Django 3.1 on 2020-11-01 00:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201028_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 0, 56, 23, 48450, tzinfo=utc), verbose_name='date_created'),
        ),
    ]
