# Generated by Django 3.1 on 2020-11-02 01:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201101_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 1, 10, 28, 958817, tzinfo=utc), verbose_name='date_created'),
        ),
    ]
