# Generated by Django 3.1 on 2020-11-02 16:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201102_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 16, 33, 59, 873663, tzinfo=utc), verbose_name='date_created'),
        ),
    ]
