# Generated by Django 3.1 on 2020-11-03 19:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201102_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 19, 1, 39, 754292, tzinfo=utc), verbose_name='date_created'),
        ),
    ]
