# Generated by Django 3.1 on 2020-11-03 19:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201103_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 19, 20, 37, 949999, tzinfo=utc), verbose_name='date_created'),
        ),
    ]
