# Generated by Django 3.1 on 2020-11-09 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201103_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 15, 58, 10, 254116, tzinfo=utc), verbose_name='date_created'),
        ),
    ]
