# Generated by Django 3.1 on 2020-11-10 11:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201110_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 11, 23, 55, 367507, tzinfo=utc), verbose_name='date_created'),
        ),
    ]
