# Generated by Django 3.1 on 2020-11-10 23:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201110_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 23, 29, 13, 21689, tzinfo=utc), verbose_name='date_created'),
        ),
    ]
