# Generated by Django 3.1 on 2020-11-11 00:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20201111_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 0, 13, 2, 320103, tzinfo=utc), verbose_name='date_created'),
        ),
    ]
