# Generated by Django 3.1 on 2020-11-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_admin_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='thumbnail',
            field=models.ImageField(default='default', upload_to='images/'),
            preserve_default=False,
        ),
    ]
