# Generated by Django 3.1 on 2020-11-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_upload_thumbnail2'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='thumbnail3',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='thumbnail4',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='thumbnail5',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
