# Generated by Django 3.1 on 2020-11-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20201111_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2006-10-25'),
            preserve_default=False,
        ),
    ]
